# Generated by Django 4.0.3 on 2022-03-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='file_name',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
