# Generated by Django 4.0.3 on 2022-04-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_alter_receita_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='file_name',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='receita',
            name='nome_receita',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
